# Copyright (c) 2025 Zensical and contributors

# SPDX-License-Identifier: MIT
# Third-party contributions licensed under DCO

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions:
  attestations: write # Required for attestations
  id-token: write     # Required for OIDC

jobs:
  build:
    name: Wheel (${{ matrix.name }}, ${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux
            platform: linux
            os: ubuntu-latest
            target: x86_64
            manylinux: auto
          - name: Linux
            platform: linux
            os: ubuntu-latest
            target: x86
            manylinux: auto
          - name: Linux
            platform: linux
            os: ubuntu-latest
            target: aarch64
            manylinux: auto
          - name: Linux
            platform: linux
            os: ubuntu-latest
            target: armv7
            manylinux: auto
          - name: Linux Musl
            platform: musllinux
            os: ubuntu-latest
            target: x86_64
            manylinux: musllinux_1_2
          - name: Linux Musl
            platform: musllinux
            os: ubuntu-latest
            target: x86
            manylinux: musllinux_1_2
          - name: Linux Musl
            platform: musllinux
            os: ubuntu-latest
            target: aarch64
            manylinux: musllinux_1_2
          - name: Linux Musl
            platform: musllinux
            os: ubuntu-latest
            target: armv7
            manylinux: musllinux_1_2
          - name: Windows
            platform: windows
            os: windows-latest
            target: x64
          - name: Windows
            platform: windows
            os: windows-latest
            target: x86
          - name: macOS
            platform: macos
            os: macos-15-intel
            target: x86_64
          - name: macOS
            platform: macos
            os: macos-15
            target: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref || github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Prepare build
        run: python scripts/prepare.py

      - name: Build artifact
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out artifacts
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          sccache: >
            ${{ !startsWith(github.event.pull_request.head.ref, 'release/') }}

      - name: Create artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          show-summary: false
          subject-path: artifacts/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.platform }}-${{ matrix.target }}
          path: artifacts/*
